[package]
name = "ango"
version = "0.1.0"
authors = ["Mark Nguyen <misteraznkid@yahoo.com>"]

[dependencies]
sodium = { git = "https://github.com/nguyenmp/libsodium-sys" }
uuid = { version = "0.7", features = ["v4"] }